/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package cn.gitos.aurthur.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RcvblFlow extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RcvblFlow\",\"namespace\":\"cn.gitos.aurthur.model.avro\",\"fields\":[{\"name\":\"rcvbl_amt_id\",\"type\":\"long\"},{\"name\":\"amt_type\",\"type\":\"string\"},{\"name\":\"rcvbl_ym\",\"type\":\"string\"},{\"name\":\"cons_no\",\"type\":\"string\"},{\"name\":\"org_no\",\"type\":\"string\"},{\"name\":\"pay_mode\",\"type\":\"string\"},{\"name\":\"t_pq\",\"type\":\"double\"},{\"name\":\"rcvbl_amt\",\"type\":\"double\"},{\"name\":\"rcved_amt\",\"type\":\"double\"},{\"name\":\"own_amt\",\"type\":\"double\"},{\"name\":\"released_date\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long rcvbl_amt_id;
  @Deprecated public java.lang.CharSequence amt_type;
  @Deprecated public java.lang.CharSequence rcvbl_ym;
  @Deprecated public java.lang.CharSequence cons_no;
  @Deprecated public java.lang.CharSequence org_no;
  @Deprecated public java.lang.CharSequence pay_mode;
  @Deprecated public double t_pq;
  @Deprecated public double rcvbl_amt;
  @Deprecated public double rcved_amt;
  @Deprecated public double own_amt;
  @Deprecated public java.lang.CharSequence released_date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public RcvblFlow() {}

  /**
   * All-args constructor.
   */
  public RcvblFlow(java.lang.Long rcvbl_amt_id, java.lang.CharSequence amt_type, java.lang.CharSequence rcvbl_ym, java.lang.CharSequence cons_no, java.lang.CharSequence org_no, java.lang.CharSequence pay_mode, java.lang.Double t_pq, java.lang.Double rcvbl_amt, java.lang.Double rcved_amt, java.lang.Double own_amt, java.lang.CharSequence released_date) {
    this.rcvbl_amt_id = rcvbl_amt_id;
    this.amt_type = amt_type;
    this.rcvbl_ym = rcvbl_ym;
    this.cons_no = cons_no;
    this.org_no = org_no;
    this.pay_mode = pay_mode;
    this.t_pq = t_pq;
    this.rcvbl_amt = rcvbl_amt;
    this.rcved_amt = rcved_amt;
    this.own_amt = own_amt;
    this.released_date = released_date;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rcvbl_amt_id;
    case 1: return amt_type;
    case 2: return rcvbl_ym;
    case 3: return cons_no;
    case 4: return org_no;
    case 5: return pay_mode;
    case 6: return t_pq;
    case 7: return rcvbl_amt;
    case 8: return rcved_amt;
    case 9: return own_amt;
    case 10: return released_date;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rcvbl_amt_id = (java.lang.Long)value$; break;
    case 1: amt_type = (java.lang.CharSequence)value$; break;
    case 2: rcvbl_ym = (java.lang.CharSequence)value$; break;
    case 3: cons_no = (java.lang.CharSequence)value$; break;
    case 4: org_no = (java.lang.CharSequence)value$; break;
    case 5: pay_mode = (java.lang.CharSequence)value$; break;
    case 6: t_pq = (java.lang.Double)value$; break;
    case 7: rcvbl_amt = (java.lang.Double)value$; break;
    case 8: rcved_amt = (java.lang.Double)value$; break;
    case 9: own_amt = (java.lang.Double)value$; break;
    case 10: released_date = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'rcvbl_amt_id' field.
   */
  public java.lang.Long getRcvblAmtId() {
    return rcvbl_amt_id;
  }

  /**
   * Sets the value of the 'rcvbl_amt_id' field.
   * @param value the value to set.
   */
  public void setRcvblAmtId(java.lang.Long value) {
    this.rcvbl_amt_id = value;
  }

  /**
   * Gets the value of the 'amt_type' field.
   */
  public java.lang.CharSequence getAmtType() {
    return amt_type;
  }

  /**
   * Sets the value of the 'amt_type' field.
   * @param value the value to set.
   */
  public void setAmtType(java.lang.CharSequence value) {
    this.amt_type = value;
  }

  /**
   * Gets the value of the 'rcvbl_ym' field.
   */
  public java.lang.CharSequence getRcvblYm() {
    return rcvbl_ym;
  }

  /**
   * Sets the value of the 'rcvbl_ym' field.
   * @param value the value to set.
   */
  public void setRcvblYm(java.lang.CharSequence value) {
    this.rcvbl_ym = value;
  }

  /**
   * Gets the value of the 'cons_no' field.
   */
  public java.lang.CharSequence getConsNo() {
    return cons_no;
  }

  /**
   * Sets the value of the 'cons_no' field.
   * @param value the value to set.
   */
  public void setConsNo(java.lang.CharSequence value) {
    this.cons_no = value;
  }

  /**
   * Gets the value of the 'org_no' field.
   */
  public java.lang.CharSequence getOrgNo() {
    return org_no;
  }

  /**
   * Sets the value of the 'org_no' field.
   * @param value the value to set.
   */
  public void setOrgNo(java.lang.CharSequence value) {
    this.org_no = value;
  }

  /**
   * Gets the value of the 'pay_mode' field.
   */
  public java.lang.CharSequence getPayMode() {
    return pay_mode;
  }

  /**
   * Sets the value of the 'pay_mode' field.
   * @param value the value to set.
   */
  public void setPayMode(java.lang.CharSequence value) {
    this.pay_mode = value;
  }

  /**
   * Gets the value of the 't_pq' field.
   */
  public java.lang.Double getTPq() {
    return t_pq;
  }

  /**
   * Sets the value of the 't_pq' field.
   * @param value the value to set.
   */
  public void setTPq(java.lang.Double value) {
    this.t_pq = value;
  }

  /**
   * Gets the value of the 'rcvbl_amt' field.
   */
  public java.lang.Double getRcvblAmt() {
    return rcvbl_amt;
  }

  /**
   * Sets the value of the 'rcvbl_amt' field.
   * @param value the value to set.
   */
  public void setRcvblAmt(java.lang.Double value) {
    this.rcvbl_amt = value;
  }

  /**
   * Gets the value of the 'rcved_amt' field.
   */
  public java.lang.Double getRcvedAmt() {
    return rcved_amt;
  }

  /**
   * Sets the value of the 'rcved_amt' field.
   * @param value the value to set.
   */
  public void setRcvedAmt(java.lang.Double value) {
    this.rcved_amt = value;
  }

  /**
   * Gets the value of the 'own_amt' field.
   */
  public java.lang.Double getOwnAmt() {
    return own_amt;
  }

  /**
   * Sets the value of the 'own_amt' field.
   * @param value the value to set.
   */
  public void setOwnAmt(java.lang.Double value) {
    this.own_amt = value;
  }

  /**
   * Gets the value of the 'released_date' field.
   */
  public java.lang.CharSequence getReleasedDate() {
    return released_date;
  }

  /**
   * Sets the value of the 'released_date' field.
   * @param value the value to set.
   */
  public void setReleasedDate(java.lang.CharSequence value) {
    this.released_date = value;
  }

  /** Creates a new RcvblFlow RecordBuilder */
  public static RcvblFlow.Builder newBuilder() {
    return new RcvblFlow.Builder();
  }
  
  /** Creates a new RcvblFlow RecordBuilder by copying an existing Builder */
  public static RcvblFlow.Builder newBuilder(RcvblFlow.Builder other) {
    return new RcvblFlow.Builder(other);
  }
  
  /** Creates a new RcvblFlow RecordBuilder by copying an existing RcvblFlow instance */
  public static RcvblFlow.Builder newBuilder(RcvblFlow other) {
    return new RcvblFlow.Builder(other);
  }
  
  /**
   * RecordBuilder for RcvblFlow instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RcvblFlow>
    implements org.apache.avro.data.RecordBuilder<RcvblFlow> {

    private long rcvbl_amt_id;
    private java.lang.CharSequence amt_type;
    private java.lang.CharSequence rcvbl_ym;
    private java.lang.CharSequence cons_no;
    private java.lang.CharSequence org_no;
    private java.lang.CharSequence pay_mode;
    private double t_pq;
    private double rcvbl_amt;
    private double rcved_amt;
    private double own_amt;
    private java.lang.CharSequence released_date;

    /** Creates a new Builder */
    private Builder() {
      super(RcvblFlow.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(RcvblFlow.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rcvbl_amt_id)) {
        this.rcvbl_amt_id = data().deepCopy(fields()[0].schema(), other.rcvbl_amt_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amt_type)) {
        this.amt_type = data().deepCopy(fields()[1].schema(), other.amt_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rcvbl_ym)) {
        this.rcvbl_ym = data().deepCopy(fields()[2].schema(), other.rcvbl_ym);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cons_no)) {
        this.cons_no = data().deepCopy(fields()[3].schema(), other.cons_no);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.org_no)) {
        this.org_no = data().deepCopy(fields()[4].schema(), other.org_no);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.pay_mode)) {
        this.pay_mode = data().deepCopy(fields()[5].schema(), other.pay_mode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.t_pq)) {
        this.t_pq = data().deepCopy(fields()[6].schema(), other.t_pq);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rcvbl_amt)) {
        this.rcvbl_amt = data().deepCopy(fields()[7].schema(), other.rcvbl_amt);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.rcved_amt)) {
        this.rcved_amt = data().deepCopy(fields()[8].schema(), other.rcved_amt);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.own_amt)) {
        this.own_amt = data().deepCopy(fields()[9].schema(), other.own_amt);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.released_date)) {
        this.released_date = data().deepCopy(fields()[10].schema(), other.released_date);
        fieldSetFlags()[10] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RcvblFlow instance */
    private Builder(RcvblFlow other) {
            super(RcvblFlow.SCHEMA$);
      if (isValidValue(fields()[0], other.rcvbl_amt_id)) {
        this.rcvbl_amt_id = data().deepCopy(fields()[0].schema(), other.rcvbl_amt_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amt_type)) {
        this.amt_type = data().deepCopy(fields()[1].schema(), other.amt_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rcvbl_ym)) {
        this.rcvbl_ym = data().deepCopy(fields()[2].schema(), other.rcvbl_ym);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cons_no)) {
        this.cons_no = data().deepCopy(fields()[3].schema(), other.cons_no);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.org_no)) {
        this.org_no = data().deepCopy(fields()[4].schema(), other.org_no);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.pay_mode)) {
        this.pay_mode = data().deepCopy(fields()[5].schema(), other.pay_mode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.t_pq)) {
        this.t_pq = data().deepCopy(fields()[6].schema(), other.t_pq);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rcvbl_amt)) {
        this.rcvbl_amt = data().deepCopy(fields()[7].schema(), other.rcvbl_amt);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.rcved_amt)) {
        this.rcved_amt = data().deepCopy(fields()[8].schema(), other.rcved_amt);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.own_amt)) {
        this.own_amt = data().deepCopy(fields()[9].schema(), other.own_amt);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.released_date)) {
        this.released_date = data().deepCopy(fields()[10].schema(), other.released_date);
        fieldSetFlags()[10] = true;
      }
    }

    /** Gets the value of the 'rcvbl_amt_id' field */
    public java.lang.Long getRcvblAmtId() {
      return rcvbl_amt_id;
    }
    
    /** Sets the value of the 'rcvbl_amt_id' field */
    public RcvblFlow.Builder setRcvblAmtId(long value) {
      validate(fields()[0], value);
      this.rcvbl_amt_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'rcvbl_amt_id' field has been set */
    public boolean hasRcvblAmtId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'rcvbl_amt_id' field */
    public RcvblFlow.Builder clearRcvblAmtId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'amt_type' field */
    public java.lang.CharSequence getAmtType() {
      return amt_type;
    }
    
    /** Sets the value of the 'amt_type' field */
    public RcvblFlow.Builder setAmtType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.amt_type = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'amt_type' field has been set */
    public boolean hasAmtType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'amt_type' field */
    public RcvblFlow.Builder clearAmtType() {
      amt_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'rcvbl_ym' field */
    public java.lang.CharSequence getRcvblYm() {
      return rcvbl_ym;
    }
    
    /** Sets the value of the 'rcvbl_ym' field */
    public RcvblFlow.Builder setRcvblYm(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.rcvbl_ym = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'rcvbl_ym' field has been set */
    public boolean hasRcvblYm() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'rcvbl_ym' field */
    public RcvblFlow.Builder clearRcvblYm() {
      rcvbl_ym = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'cons_no' field */
    public java.lang.CharSequence getConsNo() {
      return cons_no;
    }
    
    /** Sets the value of the 'cons_no' field */
    public RcvblFlow.Builder setConsNo(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.cons_no = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'cons_no' field has been set */
    public boolean hasConsNo() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'cons_no' field */
    public RcvblFlow.Builder clearConsNo() {
      cons_no = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'org_no' field */
    public java.lang.CharSequence getOrgNo() {
      return org_no;
    }
    
    /** Sets the value of the 'org_no' field */
    public RcvblFlow.Builder setOrgNo(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.org_no = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'org_no' field has been set */
    public boolean hasOrgNo() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'org_no' field */
    public RcvblFlow.Builder clearOrgNo() {
      org_no = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'pay_mode' field */
    public java.lang.CharSequence getPayMode() {
      return pay_mode;
    }
    
    /** Sets the value of the 'pay_mode' field */
    public RcvblFlow.Builder setPayMode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.pay_mode = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'pay_mode' field has been set */
    public boolean hasPayMode() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'pay_mode' field */
    public RcvblFlow.Builder clearPayMode() {
      pay_mode = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 't_pq' field */
    public java.lang.Double getTPq() {
      return t_pq;
    }
    
    /** Sets the value of the 't_pq' field */
    public RcvblFlow.Builder setTPq(double value) {
      validate(fields()[6], value);
      this.t_pq = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 't_pq' field has been set */
    public boolean hasTPq() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 't_pq' field */
    public RcvblFlow.Builder clearTPq() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'rcvbl_amt' field */
    public java.lang.Double getRcvblAmt() {
      return rcvbl_amt;
    }
    
    /** Sets the value of the 'rcvbl_amt' field */
    public RcvblFlow.Builder setRcvblAmt(double value) {
      validate(fields()[7], value);
      this.rcvbl_amt = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'rcvbl_amt' field has been set */
    public boolean hasRcvblAmt() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'rcvbl_amt' field */
    public RcvblFlow.Builder clearRcvblAmt() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'rcved_amt' field */
    public java.lang.Double getRcvedAmt() {
      return rcved_amt;
    }
    
    /** Sets the value of the 'rcved_amt' field */
    public RcvblFlow.Builder setRcvedAmt(double value) {
      validate(fields()[8], value);
      this.rcved_amt = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'rcved_amt' field has been set */
    public boolean hasRcvedAmt() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'rcved_amt' field */
    public RcvblFlow.Builder clearRcvedAmt() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'own_amt' field */
    public java.lang.Double getOwnAmt() {
      return own_amt;
    }
    
    /** Sets the value of the 'own_amt' field */
    public RcvblFlow.Builder setOwnAmt(double value) {
      validate(fields()[9], value);
      this.own_amt = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'own_amt' field has been set */
    public boolean hasOwnAmt() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'own_amt' field */
    public RcvblFlow.Builder clearOwnAmt() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'released_date' field */
    public java.lang.CharSequence getReleasedDate() {
      return released_date;
    }
    
    /** Sets the value of the 'released_date' field */
    public RcvblFlow.Builder setReleasedDate(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.released_date = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'released_date' field has been set */
    public boolean hasReleasedDate() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'released_date' field */
    public RcvblFlow.Builder clearReleasedDate() {
      released_date = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public RcvblFlow build() {
      try {
        RcvblFlow record = new RcvblFlow();
        record.rcvbl_amt_id = fieldSetFlags()[0] ? this.rcvbl_amt_id : (java.lang.Long) defaultValue(fields()[0]);
        record.amt_type = fieldSetFlags()[1] ? this.amt_type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.rcvbl_ym = fieldSetFlags()[2] ? this.rcvbl_ym : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.cons_no = fieldSetFlags()[3] ? this.cons_no : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.org_no = fieldSetFlags()[4] ? this.org_no : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.pay_mode = fieldSetFlags()[5] ? this.pay_mode : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.t_pq = fieldSetFlags()[6] ? this.t_pq : (java.lang.Double) defaultValue(fields()[6]);
        record.rcvbl_amt = fieldSetFlags()[7] ? this.rcvbl_amt : (java.lang.Double) defaultValue(fields()[7]);
        record.rcved_amt = fieldSetFlags()[8] ? this.rcved_amt : (java.lang.Double) defaultValue(fields()[8]);
        record.own_amt = fieldSetFlags()[9] ? this.own_amt : (java.lang.Double) defaultValue(fields()[9]);
        record.released_date = fieldSetFlags()[10] ? this.released_date : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
